"""
Main FastAPI application entry point for Vercel deployment.
This file is auto-generated by fastapi-gen.
"""
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
env_path = Path(__file__).parent.parent / '.env'
load_dotenv(dotenv_path=env_path)

# HACK: Add the project root to the Python path
project_root = Path(__file__).parent
sys.path.append(str(project_root))

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# Import your application using absolute imports
from config import settings
from src.infrastructure.api.routes import api_router



def create_app() -> FastAPI:
    """Create and configure the FastAPI application."""
    app = FastAPI(
        title=settings.APP_NAME,
        description="A FastAPI application with clean architecture",
        version="0.1.0",
        docs_url="/docs",
        redoc_url="/redoc",
    )

    # Add CORS middleware
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.ALLOWED_ORIGINS,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
        expose_headers=["set-cookie"],  # Important for cookies to be set in the browser
    )

    # Include API routes
    app.include_router(api_router, prefix=settings.API_V1_STR)

    return app

# Create the FastAPI application
app = create_app()

# This is needed for Vercel's serverless functions
# It creates a handler that Vercel can use to run the FastAPI app
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("index:app", host="0.0.0.0", port=8000, reload=True)
