name: Deploy Frontend to S3

on:
  push:
    branches: [ main ]
    paths:
      - 'front/**'
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1
  AWS_S3_BUCKET_NAME: tomin-ai

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: front
        run: npm ci

      - name: Build Next.js
        working-directory: front
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3 Bucket
        working-directory: front
        run: |
          aws s3 sync out/ s3://${{ env.AWS_S3_BUCKET_NAME }} --delete \
          --cache-control "max-age=31536000,public"
